# Generated by Django 3.1.4 on 2021-01-20 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aseguramiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAseguramiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('apellidos', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9\\s+()-]+\\Z'), "Introduzca un 'NÚMERO DE TELÉFONO' válido.", 'error')], verbose_name='teléfono personal')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('fechaInicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fechaFin', models.DateTimeField(verbose_name='fecha de fin')),
                ('diaCompleto', models.BooleanField(default=False, verbose_name='todo el día')),
                ('cantidadParticipante', models.IntegerField(null=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trabajador')),
                ('tipoActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoactividad')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='core.Trabajador'),
        ),
        migrations.CreateModel(
            name='AseguramientoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=255, null=True)),
                ('observacion', models.TextField(max_length=255, null=True)),
                ('aseguramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aseguramiento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='AseguramientoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('aseguramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aseguramiento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local')),
            ],
        ),
        migrations.AddField(
            model_name='aseguramiento',
            name='tipoAseguramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoaseguramiento'),
        ),
    ]
