# Generated by Django 3.1.4 on 2021-01-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='horaFin',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de fin'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de inicio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaFin',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaInicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
