# Generated by Django 3.1.4 on 2021-01-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210123_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='responsables',
            field=models.ManyToManyField(to='core.Trabajador'),
        ),
    ]
