# Generated by Django 3.1.4 on 2021-01-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210123_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='responsables',
            field=models.ManyToManyField(blank=True, to='core.Trabajador'),
        ),
    ]
