# Generated by Django 3.1.4 on 2021-04-13 14:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210123_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('fechaInicio', models.DateField(verbose_name='fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='fecha de fin')),
                ('horaInicio', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('horaFin', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local')),
                ('tipoActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoactividad')),
            ],
            bases=(core.models.ValidateOnSaveMixin, models.Model),
        ),
    ]
