# Generated by Django 3.1.4 on 2021-04-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horaFin',
            field=models.TimeField(verbose_name='hora de fin'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaInicio',
            field=models.TimeField(verbose_name='hora de inicio'),
        ),
    ]
