# Generated by Django 3.1.4 on 2021-06-17 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210413_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='telefonoFijo',
            field=models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9\\s+()-]+\\Z'), "Introduzca un 'NÚMERO DE TELÉFONO' válido.", 'error')], verbose_name='teléfono fijo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipoUsuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
    ]
